/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;

export type PaymentTerms = { advance: null } | { credit30: null };
export type POStatus = { draft: null } | { approved: null } | { received: null };
export type MRNStatus = { pending: null } | { approved: null };

export interface Supplier { id: bigint; code: string; name: string; address: string; contactPerson: string; phone: string; email: string; gstNo: string; itemsSupplied: string[]; estimatedDeliveryDays: bigint; paymentTerms: PaymentTerms; active: boolean; }
export interface Item { id: bigint; code: string; name: string; unit: string; category: string; currentStock: number; minimumStock: number; }
export interface POItem { itemCode: string; itemName: string; unit: string; quantity: number; rate: number; amount: number; }
export interface PurchaseOrder { id: bigint; code: string; supplierId: bigint; supplierName: string; orderDate: string; expectedDelivery: string; items: POItem[]; totalAmount: number; status: POStatus; remarks: string; month: bigint; year: bigint; }
export interface MRNItem { slNo: bigint; itemCode: string; itemDescription: string; unit: string; quantity: number; remark: string; }
export interface MaterialsRequest { id: bigint; code: string; requestDate: string; month: bigint; year: bigint; items: MRNItem[]; requestedBy: string; approvedBy: string; status: MRNStatus; }
export interface GRNItem { itemCode: string; itemName: string; unit: string; orderedQty: number; receivedQty: number; rate: number; amount: number; }
export interface GRN { id: bigint; code: string; poId: bigint; supplierId: bigint; supplierName: string; receivedDate: string; items: GRNItem[]; totalAmount: number; receivedBy: string; remarks: string; month: bigint; year: bigint; }
export interface DCItem { itemCode: string; itemName: string; unit: string; quantity: number; remarks: string; }
export interface DeliveryChallan { id: bigint; code: string; dcDate: string; deliverTo: string; projectName: string; items: DCItem[]; preparedBy: string; authorizedBy: string; month: bigint; year: bigint; }
export interface MCRItem { itemCode: string; itemName: string; unit: string; openingStock: number; received: number; issued: number; closingStock: number; }

export interface backendInterface {
    _initializeAccessControlWithSecret(token: string): Promise<void>;
    createSupplier(name: string, address: string, contactPerson: string, phone: string, email: string, gstNo: string, itemsSupplied: string[], estimatedDeliveryDays: bigint, paymentTerms: PaymentTerms): Promise<Supplier>;
    getAllSuppliers(): Promise<Supplier[]>;
    getSupplierById(id: bigint): Promise<Option<Supplier>>;
    updateSupplier(id: bigint, name: string, address: string, contactPerson: string, phone: string, email: string, gstNo: string, itemsSupplied: string[], estimatedDeliveryDays: bigint, paymentTerms: PaymentTerms): Promise<boolean>;
    createItem(name: string, unit: string, category: string, minimumStock: number): Promise<Item>;
    getAllItems(): Promise<Item[]>;
    updateItemStock(id: bigint, stock: number): Promise<boolean>;
    createPO(supplierId: bigint, supplierName: string, orderDate: string, expectedDelivery: string, items: POItem[], totalAmount: number, remarks: string, month: bigint, year: bigint): Promise<PurchaseOrder>;
    getAllPOs(): Promise<PurchaseOrder[]>;
    getPOById(id: bigint): Promise<Option<PurchaseOrder>>;
    updatePOStatus(id: bigint, status: POStatus): Promise<boolean>;
    getPOsByFilter(month: bigint, year: bigint, supplierId: bigint): Promise<PurchaseOrder[]>;
    createMRN(requestDate: string, month: bigint, year: bigint, items: MRNItem[], requestedBy: string, approvedBy: string): Promise<MaterialsRequest>;
    getAllMRNs(): Promise<MaterialsRequest[]>;
    getMRNById(id: bigint): Promise<Option<MaterialsRequest>>;
    approveMRN(id: bigint, approvedBy: string): Promise<boolean>;
    createGRN(poId: bigint, supplierId: bigint, supplierName: string, receivedDate: string, items: GRNItem[], totalAmount: number, receivedBy: string, remarks: string, month: bigint, year: bigint): Promise<GRN>;
    getAllGRNs(): Promise<GRN[]>;
    getGRNById(id: bigint): Promise<Option<GRN>>;
    getGRNsByFilter(month: bigint, year: bigint, supplierId: bigint): Promise<GRN[]>;
    createDC(dcDate: string, deliverTo: string, projectName: string, items: DCItem[], preparedBy: string, authorizedBy: string, month: bigint, year: bigint): Promise<DeliveryChallan>;
    getAllDCs(): Promise<DeliveryChallan[]>;
    getDCById(id: bigint): Promise<Option<DeliveryChallan>>;
    getClosingStock(): Promise<Item[]>;
    getMCR(month: bigint, year: bigint): Promise<MCRItem[]>;
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: any) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<any>, private processError?: (error: unknown) => never){}

    async _initializeAccessControlWithSecret(token: string): Promise<void> { return (this.actor as any)._initializeAccessControlWithSecret(token); }
    async createSupplier(...args: any[]): Promise<Supplier> { return (this.actor as any).createSupplier(...args); }
    async getAllSuppliers(): Promise<Supplier[]> { return (this.actor as any).getAllSuppliers(); }
    async getSupplierById(id: bigint): Promise<Option<Supplier>> { return (this.actor as any).getSupplierById(id); }
    async updateSupplier(...args: any[]): Promise<boolean> { return (this.actor as any).updateSupplier(...args); }
    async createItem(...args: any[]): Promise<Item> { return (this.actor as any).createItem(...args); }
    async getAllItems(): Promise<Item[]> { return (this.actor as any).getAllItems(); }
    async updateItemStock(id: bigint, stock: number): Promise<boolean> { return (this.actor as any).updateItemStock(id, stock); }
    async createPO(...args: any[]): Promise<PurchaseOrder> { return (this.actor as any).createPO(...args); }
    async getAllPOs(): Promise<PurchaseOrder[]> { return (this.actor as any).getAllPOs(); }
    async getPOById(id: bigint): Promise<Option<PurchaseOrder>> { return (this.actor as any).getPOById(id); }
    async updatePOStatus(id: bigint, status: POStatus): Promise<boolean> { return (this.actor as any).updatePOStatus(id, status); }
    async getPOsByFilter(month: bigint, year: bigint, supplierId: bigint): Promise<PurchaseOrder[]> { return (this.actor as any).getPOsByFilter(month, year, supplierId); }
    async createMRN(...args: any[]): Promise<MaterialsRequest> { return (this.actor as any).createMRN(...args); }
    async getAllMRNs(): Promise<MaterialsRequest[]> { return (this.actor as any).getAllMRNs(); }
    async getMRNById(id: bigint): Promise<Option<MaterialsRequest>> { return (this.actor as any).getMRNById(id); }
    async approveMRN(id: bigint, approvedBy: string): Promise<boolean> { return (this.actor as any).approveMRN(id, approvedBy); }
    async createGRN(...args: any[]): Promise<GRN> { return (this.actor as any).createGRN(...args); }
    async getAllGRNs(): Promise<GRN[]> { return (this.actor as any).getAllGRNs(); }
    async getGRNById(id: bigint): Promise<Option<GRN>> { return (this.actor as any).getGRNById(id); }
    async getGRNsByFilter(month: bigint, year: bigint, supplierId: bigint): Promise<GRN[]> { return (this.actor as any).getGRNsByFilter(month, year, supplierId); }
    async createDC(...args: any[]): Promise<DeliveryChallan> { return (this.actor as any).createDC(...args); }
    async getAllDCs(): Promise<DeliveryChallan[]> { return (this.actor as any).getAllDCs(); }
    async getDCById(id: bigint): Promise<Option<DeliveryChallan>> { return (this.actor as any).getDCById(id); }
    async getClosingStock(): Promise<Item[]> { return (this.actor as any).getClosingStock(); }
    async getMCR(month: bigint, year: bigint): Promise<MCRItem[]> { return (this.actor as any).getMCR(month, year); }
}

export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) { this._blob = blob; }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob { return new ExternalBlob(url, null); }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([new Uint8Array(blob)], { type: 'application/octet-stream' }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) return this._blob;
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string { return this.directURL; }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob { this.onProgress = onProgress; return this; }
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}

export function createActor(canisterId: string, _uploadFile: (file: any) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<any>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({ ...options.agentOptions });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, { agent, canisterId, ...options.actorOptions });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
